applications:
  mod:
    questions:
      - "In-game nickname? [Bot-Proof]"
      - "How old are you?"
      - "What is your timezone?"
      - "What would you rate your plugin knowledge as?"
      - "Why do you want to be a mod?"
      - "How many hours can you commit weekly?"
  builder:
    questions:
      - "In-game nickname? [Bot-Proof]"
      - "What is your building experience?"
      - "Are you familiar with WorldEdit and VoxelSniper?"
      - "How many hours can you commit weekly?"
      - "Have you been a builder previously in any other servers?"
      - "Can you provide screenshots of your builds? [Send IMGUR links]"
  lore:
    questions:
      - "In-game nickname? [Bot-Proof]"
      - "Why are you interested in lore?"
      - "What is your favorite comic-book in DC Comics?"
      - "What would you rate your knowledge on DC Comics Characters as?"
      - "Any specific Characters you're very familiar with?"
      - "How well can you write for events?"
      - "How active will you be?"
      - "What is your timezone?"

#need to add permission setup...