name: ApplyDCU
version: 2.0
main: io.github.anonventions.applydcu.ApplyDCU
api-version: 1.20
depend: [LuckPerms]
commands:
  apply:
    description: Command to apply for roles or manage applications
    usage: /apply <role|available|accept|deny|reload>
    aliases: []
    permission: apply.use
    permission-message: You do not have permission to use this command.
permissions:
  apply.view:
    description: Allows viewing of applications
    default: op
  apply.manage:
    description: Allows managing (accept/deny) applications
    default: op
  apply.use:
    description: Allows usage of apply commands
    default: true
